import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="animated-gradient" />
        <div className="pastel-vignette" />
        <div aria-hidden className="pointer-events-none fixed inset-0 -z-[8] overflow-hidden">
          <div className="blob w-[380px] h-[380px] left-[5%] top-[15%] bg-pink-300/60" style={{animationDelay: "-1s"}} />
          <div className="blob w-[320px] h-[320px] left-[70%] top-[10%] bg-blue-300/60" style={{animationDelay: "-4s"}} />
          <div className="blob w-[360px] h-[360px] left-[20%] top-[65%] bg-green-300/60" style={{animationDelay: "-2s"}} />
          <div className="blob w-[300px] h-[300px] left-[75%] top-[70%] bg-purple-300/60" style={{animationDelay: "-6s"}} />
          <div className="blob w-[340px] h-[340px] left-[45%] top-[40%] bg-red-300/60" style={{animationDelay: "-3s"}} />
          <div className="blob w-[300px] h-[300px] left-[10%] top-[75%] bg-emerald-300/60" style={{animationDelay: "-5s"}} />
        </div>
        {children}
      </body>
    </html>
  );
}
